name: leaf2mqtt
version: 0.0.3
publish_to: 'none'
dependencies:
  dartnissanconnectna:
    git: https://gitlab.com/tobiaswkjeldsen/dartnissanconnectna
  dartnissanconnect:
    git: https://gitlab.com/sensor-freak/dartnissanconnect
  dartcarwings:
    git: https://github.com/Tobiaswk/dartcarwings
  mqtt_client: ^9.6.1
  logging: ^1.0.1
environment:
  sdk: '>=2.10.0 <3.0.0'
