name: leaf2mqtt
version: 0.0.1
publish_to: 'none'
dependencies:
  dartnissanconnectna:
    git: https://github.com/Tobiaswk/dartnissanconnectna
  dartnissanconnect:
    git: https://github.com/Tobiaswk/dartnissanconnect
  dartcarwings:
    git: https://github.com/Tobiaswk/dartcarwings

  mqtt_client: ^9.3.1

  logging: ^1.0.1

environment:
  sdk: '>=2.10.0 <3.0.0'
